// import type { Metadata } from "next";
// import "./globals.css";



// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html
//       lang="en"
//       className="h-full "
//     >
//       <body className="min-h-full flex flex-col">{children}</body>
//     </html >
//   );
// }

import { DM_Sans, Playfair_Display } from "next/font/google";
import "./globals.css";
import GlobalHeader from "./common/GlobalHeader";
import GlobalFooter from "./common/GlobalFooter";

const dmSans = DM_Sans({
  subsets: ["latin"],
  variable: "--font-body",
});

const playfair = Playfair_Display({
  subsets: ["latin"],
  variable: "--font-heading",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${dmSans.variable} ${playfair.variable}`}>
      <body>
        <GlobalHeader />
        {children}
        <GlobalFooter />
      </body>
    </html>
  );
}